### ISSUE TITLE
Is there an option to spawn without the book?

### ISSUE THREAD

**Issue by Saereth** [Porting-Dead-Mods/Nautec#3]
I was checking through the configs and data entries for the mod but I didnt see any way to stop spawning automatically with the book. In large packs these are generally disabled in favor of a combined book like akashic tome to prevent massive inventory clutter on first login. Does an option like this currently exist for Nautec and if not would you be open to adding one? thanks!

**Comment by Leclowndu93150** [comment]
Thank you for the report ! 
This was added and will be in the next update
