### ISSUE TITLE
[NeoForge 1.21.1 Suggestion]: Add REI support

### ISSUE THREAD

**Issue by vizthex123** [Porting-Dead-Mods/Nautec#6]
[REI](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) is the best remake of NEI imo, and it'd be great if this mod had native support for it.

Also applies to the 1.20.1 version if it's still supported.

_Would also be great if you added this issue tracker to the CF page's quick nav bar._

**Comment by Leclowndu93150** [comment]
There isn't an 1.20.1 version wdym

**Comment by Leclowndu93150** [comment]
Raaaah that means rewriting all the JEI stuff 😔😔😔

**Comment by vizthex123** [comment]
lol sorry. I know some mods support both, so i figured this one could too.

it's not required (assuming the [JEI bridge plugin](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks) gets ported), but it would be nice.

**Comment by Thepigcat76** [comment]
yea, not happening rn, we have too much to do
