### ISSUE TITLE
Don't use "minecraft" for recipes 

### ISSUE THREAD

**Issue by DinnerBeef** [Porting-Dead-Mods/Nautec#8]
All of these recipes should be under your ModID and not minecraft
https://github.com/Porting-Dead-Mods/Nautec/tree/main/src/generated/resources/data/minecraft/recipe

**Comment by Leclowndu93150** [comment]
who did that wtf

**Comment by Leclowndu93150** [comment]
@ReclipseTheOne

**Comment by ReclipseTheOne** [comment]
https://github.com/Porting-Dead-Mods/Nautec/commit/b6d6eed4979854003b767d6930411492b435de83
